export const ADD_CLIENT_START = "ADD_CLIENT_START"
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS"
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL"
export const START_FETCHING_CLIENTS = "START_FETCHING_CLIENTS"
export const INIT_CLIENT = "INIT_CLIENT"
export const SET_CLIENTS = "SET_CLIENTS"
export const FETCH_CLIENTS_FAILED = "FETCH_CLIENTS_FAILED"
export const SET_CLIENT_COMPANY = "SET_CLIENT_COMPANY"
export const AMMEND_CLIENT = "AMMEND_CLIENT"
export const SET_FORM_IS_VALID = "SET_FORM_IS_VALID"

export const RESET_QUOTE = "RESET_QUOTE"
export const SUBMIT_QUOTE_START = "SUBMIT_QUOTE_START"
export const SUBMIT_QUOTE_SUCCESS = "SUBMIT_QUOTE_SUCCESS"
export const SUBMIT_QUOTE_FAIL = "SUBMIT_QUOTE_FAIL"

export const DELETE_QUOTE_START = "DELETE_QUOTE_START"
export const DELETE_QUOTE_SUCCESS = "DELETE_QUOTE_SUCCESS"
export const DELETE_QUOTE_FAIL = "DELETE_QUOTE_FAIL"

export const FETCH_QUOTES_START = "FETCH_QUOTES_START"
export const FETCH_QUOTES_SUCCESS = "FETCH_QUOTES_SUCCESS"
export const FETCH_QUOTES_FAILED = "FETCH_QUOTES_FAILED"

export const SET_EDITING_TRUE = "SET_EDITING_TRUE"
export const SET_EDITING_FALSE = "SET_EDITING_FALSE"

export const UPDATE_REDUX_STATE = "UPDATE_REDUX_STATE"
export const UPDATE_CLIENT_REDUX_FOR_EDITING = "UPDATE_CLIENT_REDUX_FOR_EDITING"

export const PDF_FORMAT_CHANGE = "PDF_FORMAT_CHANGE"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const CREATE_QUOTEDATA = "CREATE_QUOTEDATA"

export const RESET_REPORT = "RESET_REPORT"
export const CREATE_REPORT = "CREATE_REPORT"

export const SAVE_JOB_ORDER_START = "SAVE_JOB_ORDER_START"
export const SAVE_JOB_ORDER_FAIL = "SAVE_JOB_ORDER_FAIL"
export const SAVE_JOB_ORDER_SUCCESS = "SAVE_JOB_ORDER_SUCCESS"
export const FETCH_JOB_ORDER_START = "FETCH_JOB_ORDER_START"
export const FETCH_JOB_ORDER_FAIL = "FETCH_JOB_ORDER_FAIL"
export const FETCH_JOB_ORDER_SUCCESS = "FETCH_JOB_ORDER_SUCCESS"